/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema._de_ticket_dsiii_p2;

import conector.Conexion;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

import java.io.FileOutputStream;
/**
 *
 * @author antho
 */
public class ChatDialog extends javax.swing.JFrame {
 Conexion con= new Conexion();
 Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    /**
     * Creates new form ChatDialog
     */
    
    private String idTicket;
  public ChatDialog(String idTicket) {
    initComponents();
    this.idTicket = idTicket;
    cargarMensajesChat(idTicket); // Carga los mensajes al abrir
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTmensaje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAchat = new javax.swing.JTextArea();
        BTNenviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTmensaje.setToolTipText("");
        JTmensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTmensajeActionPerformed(evt);
            }
        });

        TAchat.setColumns(20);
        TAchat.setRows(5);
        jScrollPane1.setViewportView(TAchat);

        BTNenviar.setText("ENVIAR");
        BTNenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNenviarActionPerformed(evt);
            }
        });

        jLabel1.setText("CHAT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(JTmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTNenviar)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNenviar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTmensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTmensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTmensajeActionPerformed

    private void BTNenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNenviarActionPerformed
   enviarMensaje("tecnico", idTicket); 
    }//GEN-LAST:event_BTNenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatDialog(idTicket).setVisible(true);
            }
        });
    }

    
    private void enviarMensaje(String remitente, String idTicket) {
    String mensaje = JTmensaje.getText().trim();
    if (mensaje.isEmpty()) {
        return;
    }
   conet = con.getConnection();
    try {
    
        String sql = "INSERT INTO mensajes_chat (id_ticket, remitente, mensaje) VALUES (?, ?, ?)";
        PreparedStatement pst = conet.prepareStatement(sql);
        pst.setString(1, idTicket);
        pst.setString(2, remitente); // técnico o cliente
        pst.setString(3, mensaje);
        pst.executeUpdate();

        JTmensaje.setText(""); // limpiar el campo de entrada
        cargarMensajesChat(idTicket); // refrescar el área de chat
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al enviar mensaje: " + e.getMessage());
    }
}
    private void cargarMensajesChat(String idTicket) {
    TAchat.setText(""); // limpiar área

    try {
        Connection conet = con.getConnection();
        String sql = "SELECT remitente, mensaje, fecha_envio FROM mensajes_chat WHERE id_ticket = ? ORDER BY fecha_envio ASC";
        PreparedStatement pst = conet.prepareStatement(sql);
        pst.setString(1, idTicket);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            String remitente = rs.getString("remitente");
            String mensaje = rs.getString("mensaje");
            String fecha = rs.getString("fecha_envio");

            TAchat.append(remitente + " [" + fecha + "]:\n" + mensaje + "\n\n");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar el chat: " + e.getMessage());
    }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNenviar;
    private javax.swing.JTextField JTmensaje;
    private javax.swing.JTextArea TAchat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
